---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yml
  - clusterrole.yml
  - clusterrolebinding.yml
  - role.yml
  - rolebinding.yml
  - deployment.yml
  - storageclass.yml

configMapGenerator:
  - name: hostpath-provisioner
    options:
      labels:
        app.kubernetes.io/name: hostpath-provisioner
        app.kubernetes.io/component: operator
    literals:
      - HOSTPATH_PROVISIONER_NAME=hostpath
      - NODE_HOST_PATH=/var/lib/volumes

images:
  - name: hostpath-provisioner
    newName: quay.io/rimusz/hostpath-provisioner
    newTag: "v0.2.5"

...
