---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: hostpath-provisioner-leader
  labels:
    app.kubernetes.io/name: hostpath-provisioner
    app.kubernetes.io/component: operator

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hostpath-provisioner-leader

subjects:
  - kind: ServiceAccount
    name: hostpath-provisioner

...
