---
apiVersion: storage.k8s.io/v1
kind: StorageClass

metadata:
  name: hostpath
  labels:
    app.kubernetes.io/name: hostpath-provisioner
    app.kubernetes.io/component: operator
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"

provisioner: hostpath
reclaimPolicy: Delete

...
